### ISSUE TITLE
How can use multi string annotations ?

### ISSUE THREAD

**Issue by 2ur1st** [pgraham/php-annotations#2]
Simple example does not work
```
/**
 * Class SlowWorker
 *
 * @Worker(
 *     name = "Slow Worker",
 *     speed = 5
 * )
 */
class SlowWorker {}
```
How I can use this annotations style ?

**Comment by pgraham** [comment]
Hey, I know it's 4 years on, but if you're still interested this should be fixed in v1.2.0.
